import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 * Carlos Augusto Rodas Guerra
 * 0901-17-963
 */
public class ListasSimples extends javax.swing.JFrame {
    
    DefaultTableModel Modelo = new DefaultTableModel();
    Nodo Primero;
    boolean ListaCreada = false;
    int contLista = 1;
    //Metodo para limpiar la tabla
    public void Limpiar(){
    while (Modelo.getRowCount() > 0) {
           Modelo.removeRow(0);
        }
    }
    //Metodo que crea la lista
    public void CrearLista(){
         if(ListaCreada == false){Primero = null; ListaCreada = true;}
    }
    //Metodo que inserta al principio de la lista
    public void Insertar(int Dato){
        Nodo Temporal=new Nodo(Dato); 
	Temporal.Siguiente=Primero;
	Primero=Temporal;
        JOptionPane.showMessageDialog(null,"Dato Ingresado Correctamente");
        this.txt_Valor.setText("");
        jLbl_Tamaño.setText(Integer.toString(contLista));
        contLista += 1;
        this.txt_Valor.requestFocus();
    }
    //Metodo que permite mostrar contenidos de la lista
    public void Mostrar(){
        if (Primero == null){
            JOptionPane.showMessageDialog(null,"La lista se encuentra vacia");
        }
        else
        {
            Limpiar();
            String Datos [] = new String[2];
            int cont = 0;
            Nodo aux=Primero;
            while (aux!=null)
            {
                Datos[0] = String.valueOf(cont);
                Datos[1] = String.valueOf(aux.info);
                Modelo.addRow(Datos);
                aux=aux.Siguiente;
                cont += 1;
            }	
        }
    }
    //Metodo que busca y muesta la posicion y el valor buscado
    public void Buscar(){
       if (Primero == null){
            JOptionPane.showMessageDialog(null,"La lista se encuentra vacia");
        }
        else
        {
            int cont = 1;
            String Datos [] = new String[2];
            Nodo aux=Primero;
            Limpiar();
            while (aux!=null)
            {
                Datos[0] = String.valueOf(cont);
                Datos[1] = String.valueOf(aux.info);
                if(Datos[1].equals(txt_Valor.getText()))
                {
                   Modelo.addRow(Datos);
                }
                aux=aux.Siguiente;
                cont += 1;
            }
		
        } 
    }
    // Metodo Para borrar segun se seleccione en el combo box
    public void Borrar(){
        int opc = CB_Borrar.getSelectedIndex();
        Nodo anterior=Primero;
        Nodo actual=Primero;
        Limpiar();
        int pos = Integer.parseInt(txt_Valor.getText());
        switch (opc){
            //Opcion que borra la opcion de nodo escogida
            case 0:{
                
                if (Primero == null){
                    JOptionPane.showMessageDialog(null,"La lista se encuentra vacia");
                } 
                else{
                    
                    int k=0;
                    if (pos>0){
			while (k!=pos && actual.Siguiente != null)
                            {
				anterior=actual;
				actual=actual.Siguiente;
				k++;
                            }
			anterior.Siguiente=actual.Siguiente;
                    }
                }

            }break;// Fin case 0
            //Opcion que borra el valor guardado dentro del nodo
            //Opcion que borra la primera posicion
            case 1:{
                if (Primero == null){
                    JOptionPane.showMessageDialog(null,"La lista se encuentra vacia");
                } 
                else{
                    Primero=Primero.Siguiente;
                    contLista-= 1;
                    jLbl_Tamaño.setText(Integer.toString(contLista));
                }
            }break;// Fin case 1
            //opcion que borra la ultima posicion
            case 2:{
                 if (Primero == null){
                    JOptionPane.showMessageDialog(null,"La lista se encuentra vacia");
                } 
                else{
                     
                    while (actual.Siguiente!=null)
                    {
			anterior=actual;
			actual=actual.Siguiente;
                    }
                    anterior.Siguiente=null;    
                    contLista-= 1;
                    jLbl_Tamaño.setText(Integer.toString(contLista));
                }
            }break;// Fin case 2
        }//Fin switch
       Mostrar(); 
    }
    
    public ListasSimples() {
        initComponents();

        this.Tabla.setModel(Modelo);
        Modelo.addColumn("No. Nodo");
        Modelo.addColumn("Valor del Nodo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btn_Ingresar = new javax.swing.JButton();
        txt_Valor = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_Mostar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLbl_Tamaño = new javax.swing.JLabel();
        CB_Borrar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor del nodo:");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_Mostar.setText("Mostrar Lista");
        btn_Mostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tamaño de la Lista: ");

        jLbl_Tamaño.setText("-");

        CB_Borrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.) Borrado por Posicion", "2.) Borrar Primero", "3.) Borrar Ultimo" }));

        jLabel3.setText("Seleccione Tipo de Borrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl_Tamaño))
                    .addComponent(CB_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Ingresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Buscar))
                            .addComponent(btn_Mostar)
                            .addComponent(btn_eliminar)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Ingresar)
                            .addComponent(btn_Buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Mostar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLbl_Tamaño))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        CrearLista();
        int num = Integer.parseInt(txt_Valor.getText());
        Insertar(num);
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void btn_MostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostarActionPerformed
        Mostrar();
    }//GEN-LAST:event_btn_MostarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    Borrar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListasSimples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Borrar;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JButton btn_Mostar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_Tamaño;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Valor;
    // End of variables declaration//GEN-END:variables
}
